### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by pthariensflame** [pthariensflame/Aquifer#11]
It's looking a bit bare-bones at the moment.  :)

**Comment by CodaFi** [comment]
Which audience(s) do you want it to appeal to?  I'm not sure many iOS/OS X developers want to learn about the underlying Categories, but it's also scary to hand-wave and make ridiculous Plumbing analogies...

**Comment by pthariensflame** [comment]
I'd rather we not handwave anything, but I take the point about most of our target audience not responding well to abstract math.

How about some examples?  Perhaps working on #3 will help us, too.
