### ISSUE TITLE
~> Conflicts with the Swift STL

### ISSUE THREAD

**Issue by CodaFi** [pthariensflame/Aquifer#13]
Ah, the totally foreseeable consequences of keeping every operator, no matter how private, at global scope.

**Comment by pthariensflame** [comment]
:(

**Comment by CodaFi** [comment]
I say keep it around for now, but the operator declaration has got to go... I'm not sure how this will affect the associativity of the operator.

**Comment by pthariensflame** [comment]
Very badly:  http://swiftdoc.org/swift-2/operator/tildegt/

**Comment by pthariensflame** [comment]
I say we rename it and its family.  Perhaps `~|>`, `<|~`, `|>~`, and `~<|` look decent?  Maybe?  :/

**Comment by CodaFi** [comment]
Could always double head

`~>>` / `<<~`

or double tail

`~~>` / `<~~`

**Comment by pthariensflame** [comment]
Ooh, the double tail variety doesn't look half bad to me!

**Comment by pthariensflame** [comment]
@CodaFi If you agree with `~~>` / `<~~` and `>~~` / `~~<`, then I can put together a pull request implementing that change.

**Comment by CodaFi** [comment]
:+1: 

I was trying them in a playground earlier and they had some deleterious effects on my machine with beta 6.  Hopefully you have more luck with the PR.
