### ISSUE TITLE
Move this under TypeLift?

### ISSUE THREAD

**Issue by CodaFi** [pthariensflame/Aquifer#2]
I noticed the license in the headers says this belongs to TypeLift in places.  Did you intend to publish this there (but didn't have sufficient privileges, again so sorry about that :smile:)?  Do you have any plans to move this under the purview of TypeLift at some point?

**Comment by pthariensflame** [comment]
Yes please!

**Comment by CodaFi** [comment]
I believe you have sufficient privileges to do the transfer yourself now.  If not, let me know.

**Comment by pthariensflame** [comment]
Great!  I'll do that now, then.  :)

**Comment by pthariensflame** [comment]
Done!

**Comment by CodaFi** [comment]
Ayyyy :sparkling_heart:
